papers/models.py
from django.core.exceptions import PermissionDenied
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from datetime import datetime
from django.db.models.query_utils import Q


class CustomUserManager(BaseUserManager):
    def create_user(self, username, password=None):
        if not username:
            raise ValueError('Users must have an email address')

        user = self.model(
            username=self.normalize_email(username),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password, **kwargs):
        user = self.model(
            username=username,
            is_staff=True,
            is_superuser=True,
            is_active=True,
            is_admin=True,
            **kwargs
        )
        user.set_password(password)
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.EmailField(verbose_name='email address', max_length=255, unique=True,null=False)
    first_name = models.CharField(verbose_name='first name',max_length=30,unique=False,null=False)
    last_name = models.CharField(verbose_name='last name',max_length=30,unique=False,null=True)
    street_line_1 = models.CharField(verbose_name='street_line_1', max_length=30)
    street_line_2 = models.CharField(verbose_name='street_line_2', max_length=30)
    city = models.CharField(verbose_name='city', max_length=30)
    state = models.CharField(verbose_name='state', max_length=30)
    zip_code = models.IntegerField()
    phone_number = models.CharField(verbose_name='phone number', blank=True, max_length=15)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    AUTHOR = 0
    PCM = 1
    PCC = 2
    ADMIN = 3
    UserTypes = (
        (AUTHOR, "Author"),
        (PCM, "PCM"),
        (PCC, "PCC"),
        (ADMIN, "Admin"),
        )
    user_type = models.IntegerField(choices=UserTypes, default=AUTHOR)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def get_address(self):
        return self.street_line_1 + ", " + self.street_line_2 + ", " + self.city + ", " + \
            self.state + ", " + str(self.zip_code)

    def get_full_name(self):
        # The user is identified by their email address
        return self.username

    def get_short_name(self):
        # The user is identified by their email address
        return self.username

    def __str__(self):  # __unicode__ on Python 2
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class Author(CustomUser):
    def get_author(request):
        return Author.objects.get(customuser_ptr_id=request.user.id)

    def update_user(user_id, new_user):
        users = Author.objects.filter(customuser_ptr_id=user_id)
        users.update(first_name=new_user.first_name, last_name=new_user.last_name,
                     street_line_1=new_user.street_line_1,
                     street_line_2=new_user.street_line_2, city=new_user.city, state=new_user.state,
                     zip_code=new_user.zip_code,
                     phone_number=new_user.phone_number)

    def __str__(self):
        return self.first_name + " " + self.last_name


class PCM(Author):
    def update_user(user_id, new_user):
        users = PCM.objects.filter(author_ptr_id=user_id)
        users.update(first_name=new_user.first_name, last_name=new_user.last_name,  street_line_1=new_user.street_line_1,
                     street_line_2=new_user.street_line_2,  city=new_user.city, state=new_user.state, zip_code=new_user.zip_code, phone_number=new_user.phone_number)


class PCC(CustomUser):
    pass


class Admin(CustomUser):
    pass


def concat_media_path(instance, filename):
    return 'paper/userId_' + \
           str(instance.ownedBy.id) + \
           '/paper_' + \
           str(instance.pk) + \
           '.' + filename.split('.')[-1]


class Paper(models.Model):
    file = models.FileField(null=False, blank=False, upload_to=concat_media_path)
    title = models.CharField(verbose_name='title', max_length=255,null=False)
    abstract = models.TextField(verbose_name='abstract', max_length=1000,unique=False,null=True,blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="author")
    submission_date = models.DateTimeField(editable=False)
    version = models.IntegerField(null=False, blank=False, unique=False, default=1)
    pcm_one = models.ForeignKey(PCM, related_name="FirstPCM_Assigned", null=True, blank=True)
    pcm_two = models.ForeignKey(PCM, related_name="SecondPCM_Assigned", null=True, blank=True)
    pcm_three = models.ForeignKey(PCM, related_name="ThirdPCM_Assigned", null=True, blank=True)
    rate = models.IntegerField(verbose_name="rating", null=True, blank=True,validators=[MinValueValidator(1), MaxValueValidator(5)])



    class Meta:
        unique_together = ['title', 'author', 'version']

    def save(self, *args, **kwargs):
        self.submission_date = datetime.now()
        return super(Paper, self).save(*args, **kwargs)

    def update_paper(paper_id, new_paper):
        papers = Paper.objects.filter(id=paper_id)
        papers.update(title=new_paper.title, abstract=new_paper.abstract, version=new_paper.version,
                      file=new_paper.file, submission_date=datetime.now())

    def get_papers(user_id):
        papers = Paper.objects.filter(author_id=user_id).order_by('-submission_date')
        for paper in papers:
            paper.state = "inactive"
        return papers

    def get_paper_for_review(pcm, paper_id):
        query = Q(pcm_one=pcm) | Q(pcm_two=pcm) | Q(pcm_three=pcm)
        paper = Paper.objects.get(Q(id=paper_id) & query)
        return paper

    def get_paper(paper_id, papers=None):
        if papers:
            for paper in papers:
                if paper.id == paper_id:
                    paper.state = "active"
                    return paper
        return Paper.objects.get(id=paper_id)

    def get_assigned_papers(pcm):
        papers = Paper.objects.filter(Q(pcm_one=pcm) | Q(pcm_two=pcm) | Q(pcm_three=pcm)).order_by('submission_date')
        for paper in papers:
            paper.state = "inactive"
        return papers

    def other_papers(pcm, paper_id=None):
        papers = Paper.objects.filter(~Q(author=pcm))
        for paper in papers:
            paper.state = "inactive"
        return papers

    def choosing_paper(paper_id, papers=None):
        for paper in papers:
            if paper.id == int(paper_id):
                paper.state = "active"
                return paper
        raise PermissionDenied()


class PaperAuthors(models.Model):
    paper = models.ForeignKey(Paper, null=False)
    author = models.ForeignKey(Author, null=False)

    class Meta:
        unique_together = ('paper', 'author')


class PaperRequests(models.Model):
    paper = models.ForeignKey(Paper, null=False, unique=True)
    pcm = models.ForeignKey(CustomUser, null=False)

    class Meta:
        unique_together=("paper", "pcm")

    def is_paper_requested(paper, pcm):
        return PaperRequests.objects.filter(Q(paper=paper) & Q(pcm=pcm)).exists()


class Reviews(models.Model):
    paper = models.ForeignKey(Paper, null=False, blank=False)
    reviewer = models.ForeignKey(CustomUser, verbose_name="reviewer", null=False)
    comment = models.CharField(verbose_name="comment", max_length=2000, null=False, blank=False)
    rate = models.IntegerField(verbose_name="rating", null=False, blank=False, validators=[MinValueValidator(1), MaxValueValidator(5)])

    class Meta:
        unique_together = ('paper', 'reviewer')

    def update_review(review):
        reviews = Reviews.objects.filter(paper=review.paper_id, reviewer=review.reviewer)
        reviews.update_or_create(paper=reviews.paper, reviewer=reviews.reviewer, comment=review.comment, rate=review.rate)


class PaperAssigned(models.Model):
    paper=models.ForeignKey(Paper, null=False)

    def assign_papers(self):
        paper= Paper.objects.all()
        pcm=PCM.objects.all()
        pcm_interested = PaperRequests.is_paper_requested(paper, pcm)
        other_pcm = PCM.objects.filter(~Q(author=pcm))
        all_pcm = pcm_interested + list(set(other_pcm) - set(pcm_interested))
        return all_pcm

papers/views/__init__.py
from .main import *
from .author import *
from .pcc import *
from .pcm import *
from .admin import *

papers/views/admin.py
# ADMIN Methods
from django.contrib.auth.decorators import login_required
from papers.models import Paper, Admin,PCM,PCC
from django.shortcuts import render_to_response
from django.views.generic.edit import UpdateView


'''pcc_home_buttons = [{'title': 'ASSIGN', 'link': 'pcc/paper/assign_list'},
                    {'title': 'REVIEW', 'link': '#'}]
nav_links = [{'title': 'NOTIFICATION', 'link': '#'},
             {'title': 'SETTINGS', 'link': '#'},
             {'title': 'LOGOUT', 'link': 'logout'}]
user = {
    'nav_links': nav_links,
}'''


@login_required(login_url="http://localhost:8000/login/")
def home(request):
    token = {}
    token["user"] = request.user
    token['papers'] = Paper.objects.all().order_by('submission_date')
    return render_to_response("admin/home.html", token)

def remind(request):
    token = user
    token['buttons'] = admin_home_buttons
    token["user"] = request.user
    return render_to_response("admin/home.html", token)


def manage_account(request):
    token = Admin.objects.all()
    return render_to_response("admin/manageAccount.html", token)


class ADMINPaperUpdate(UpdateView):
    model = Paper
    fields = ['title', 'pcm_one', 'pcm_two', 'pcm_three']
    template_name = "paper/read.html"
    success_url = "/admin/paper/assign_list"

    def get_context_data(self, **kwargs):
        #         paper = Paper.objects.filter(pk)
        kwargs['buttons'] = admin_home_buttons
        kwargs['nav_links'] = nav_links
        kwargs['username'] = self.request.user.first_name
        return UpdateView.get_context_data(self, **kwargs)

papers/views/author.py
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, redirect
from django.template.context_processors import csrf

from papers.form import PaperForm, ProfileUpdateForm, AuthorCreationForm
from papers.models import Paper, Author


@login_required(login_url="http://localhost:8000/login/")
def home(request, base="author/base.html"):
    if request.method == 'POST':
        form = PaperForm(request.POST, request.FILES)
        if form.is_valid():
            paper = form.save(commit=False)
            paper.ownedBy = get_user(request)
            paper.author = Author.get_author(request)
            if request.FILES.__len__() == 1:
                paper.file = request.FILES['file']
            paper.save()
            redirect_to = "/papers/"+str(paper.id)+"/success"
            return redirect(redirect_to)
    else:
        form = PaperForm()
    token = {}
    token['first_name'] = request.user.first_name
    token['title_right'] = 'Submit a new paper'
    token["user"] = request.user
    token['papers'] = Paper.get_papers(user_id=request.user.id)
    token.update(csrf(request))
    token['form'] = form
    token['base'] = base
    return render_to_response('author/home.html', token)


@login_required(login_url="http://localhost:8000/login/")
def profile_show(request, base="author/base.html"):
    token = {}
    token['first_name'] = request.user.first_name
    token['last_name'] = request.user.last_name
    token['username'] = request.user.username
    token["phone_number"] = request.user.phone_number
    token["address"] = request.user.get_address()
    token['base'] = base
    return render_to_response('user/profile/view.html', token)


def profile_edit(request, base="author/base.html"):
    token = {}
    token['first_name'] = request.user.first_name
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            Author.update_user(request.user.id, new_user)
            return redirect("profile")
    else:
        user = request.user
        form = ProfileUpdateForm(
            initial={'first_name': user.first_name, 'last_name': user.last_name, 'street_line_1': user.street_line_1,
                     'street_line_2': user.street_line_2, 'city': user.city, 'state': user.state,
                     'zip_code': user.zip_code, 'phone_number': user.phone_number})
    token.update(csrf(request))
    token['form'] = form
    token['base'] = base
    token['user'] = request.user
    return render_to_response('user/profile/edit.html', token)


def paper_view(request, paper_id, base="author/base.html"):
    token = {}
    token['first_name'] = request.user.first_name
    papers = Paper.get_papers(user_id=request.user.id)
    paper = Paper.get_paper(paper_id=int(paper_id), papers=papers)
    token['papers'] = papers
    token['paper'] = paper
    token['title_right'] = 'Paper #' + paper_id
    token['base'] = base
    return render_to_response('paper/view.html', token)


def paper_update(request, paper_id, base="author/base.html"):
    token = {}
    token['first_name'] = request.user.first_name
    papers = Paper.get_papers(user_id=request.user.id)
    paper = Paper.get_paper(paper_id=int(paper_id), papers=papers)
    token['papers'] = papers
    token['paper'] = paper

    if request.method == 'POST':
        form = PaperForm(request.POST, request.FILES, initial={'file':paper.file, 'abstract':paper.abstract, 'title':paper.title})
        if form.is_valid():
            new_paper = form.save(commit=False)
            if request.FILES.__len__() == 1:
                new_paper.file = request.FILES['file']
            new_paper.version = str(int(paper.version) + 1)
            Paper.update_paper(paper_id, new_paper)
            redirect_to = "/papers/" + str(paper.id) + "/success"
            return redirect(redirect_to)
    else:
        form = PaperForm()
    token['title_right'] = 'Update Paper #' + paper_id
    token.update(csrf(request))
    token['form'] = form
    token['base'] = base
    return render_to_response('paper/update.html', token)


def register(request):
    if request.method == 'POST':
        form = AuthorCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("http://localhost:8000/")
    else:
        form = AuthorCreationForm()
    token = {}
    token.update(csrf(request))
    token['form'] = form
    return render_to_response('registration/registration_form.html', token)

templates/paper/details.html
{% if paper %}
    <h4>{{ title_right }}</h4>
    <div class="card card-block paper-active">
        <h4 class="card-title">{{ paper.title }}</h4>
        <p class="card-text">{{ paper.abstract }}</p>
        <p class="card-text">(version        {{ paper.version }} | last updated on {{ paper.submission_date }})</p>
        <a href="/papers/{{ paper.id }}/update" class="card-link">Update</a>
    </div>
{% endif %}

templates/paper/new.html
{% load staticfiles %}
{% include 'user/base.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>SAM 2017</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
{% block content %}
	<div class="col-md-4 col-md-offset-4">
		<br>
		<form action="" method="post" enctype="multipart/form-data">
			<table>
			{% csrf_token %}
			{% for field in form %}
            <tr>
                <td><p>{{ field.label_tag }}</p></td>
                <td><p>{{ field }}</p></td>
                <td>{{ field.errors }}</td>
            </tr>
            {% endfor %}
			</table>
			<input type="submit" value="Save" />
		</form>
	</div>
{% endblock %}
</body>
</html>

{% block javascript %} {% endblock %}

templates/paper/read.html
{% load staticfiles %}
{% include 'user/base.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>SAM 2017</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
{% block content %}
	<div class="container">
		<form action="" method="post">
			{% csrf_token %}
			<table class="table table-striped">
			{% for field in form %}
			<tr>
				<td>{{ field.label_tag }}</td>
				<td>{{ field }}</td>
			</tr>
			{% endfor %}
			</table>
			<input type="submit" value="Update"/>
		</form>
	</div>
{% endblock %}
</body>
</html>

{% block javascript %} {% endblock %}

templates/paper/read_backup.html
{% load staticfiles %}
{% include 'user/base.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>SAM 2017</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
{% block content %}
	<div class="container">
		<br>
		<form action="" method="post" class="form-horizontal">
			{% csrf_token %}
			<div class="form-group">
				<label>Title</label>
				<p class="form-control-static">{{paper.title}}</p>
			</div>
			<div class="form-group">
				<label>Author</label>
				<p class="form-control-static">{{paper.author}}</p>
			</div>
			<div class="form-group">
				<label>Submission Date</label>
				<p class="form-control-static">{{paper.submission_date}}</p>
			</div>
			<div class="form-group">
				<label>Version</label>
				<p class="form-control-static">{{paper.version}}</p>
			</div>
			<div class="form-group">
				<label>PCM</label>
				<select class="form-control">
					<option disabled selected value> -- select an option -- </option>
					{% for person in persons %}
						<option value="{{person.username}}">{{person.username}}</option>
					{% endfor %}
				</select>
			</div>
			<div class="form-group">
				<label>PCM</label>
				<select class="form-control">
					<option disabled selected value> -- select an option -- </option>
					{% for person in persons %}
						<option value="{{person.username}}">{{person.username}}</option>
					{% endfor %}
				</select>
			</div>
			<div class="form-group">
				<label>PCM</label>
				<select class="form-control">
					<option disabled selected value> -- select an option -- </option>
					{% for person in persons %}
						<option value="{{person.username}}">{{person.username}}</option>
					{% endfor %}
				</select>
			</div>
			<input type="submit" value="Update" />
		</form>
	</div>
{% endblock %}
</body>
</html>

{% block javascript %} {% endblock %}

templates/paper/review.html
{% load staticfiles %}
{% include base %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                {% if paper %}
                    <div class="row">
                        <h3>Paper #{{ paper.id }}</h3>
                    </div>
                    <div class="row">
                        <strong>Paper</strong><br>
                        {{ paper.title }}<br>
                        <br>
                    </div>
                    <div class="row">
                        <strong>Abstract</strong><br>
                        {{ paper.abstract }}<br>
                        <br>
                    </div>
                    <div class="row">
                        version <strong>{{ paper.version }}</strong> | last updated on <strong>{{ paper.submission_date }}</strong>
                        <br>
                    </div>
                {% endif %}
            </div>
            <div class="col-sm-6">
                {% if paper %}
                    <div class="row">
                        <h3>Review</h3>
                    </div>
                    <form method="post">{% csrf_token %}
                        <div class="row">
                            <label for="id_comment">Comment:</label><br>
                            <textarea cols="50" id="id_comment" maxlength="1000" name="comment" rows="10">{{ comment }}</textarea>
                            <br>
                        </div>
                        <div class="row">
                            <label for="id_rate">Rate:</label><br>
                            <input id="id_rate" type="number" name="rate" value="{{ rate }}" /><br>
                            <br>
                        </div>
                        <div class="row">
                            <button type="submit" class="btn btn-primary btn-block" value="Submit Review">
                                Submit Review
                            </button>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/paper/table.html
<!DOCTYPE html>
<html>
<head>
    <title>SAM 2017</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script>
		function openPaperInfo(id){
			window.location = "/pcc/paper/" + id
		}
    </script>
</head>
<body>
	<div class="container">
		{% csrf_token %}
		<table class="table table-striped">
			{%for paper in papers %}
			<tr onclick="openPaperInfo({{paper.id}})">
				<td>{{paper.title}}</td>
				<td>{{paper.version}}</td>
				{% if show_author %}<td>{{paper.author}}</td> {% endif %}
				<td>{{paper.submission_date}}</td>
			</tr>
			{%endfor%}
		</table>
	</div>
</body>

templates/paper/update.html
{% load staticfiles %}
{% include base %}

{% block content %}
    <div class="container">
        <h2>Welcome to SAM2017</h2>
        <div class="row">
            <div class="col-sm-6">
                {% include 'author/paper/all.html' %}
            </div>
            <div class="col-sm-6">
                {% include 'author/paper/edit.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/paper/view.html
{% load staticfiles %}
{% include base %}

{% block content %}
    <div class="container">
        <h2>Welcome to SAM2017</h2>
        <div class="row">
            <div class="col-sm-6">
                {% include 'author/paper/all.html' %}
            </div>
            <div class="col-sm-6">
                {% include 'author/paper/details.html' %}
            </div>
        </div>
    </div>
{% endblock %}